// Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
// Author: Andrew Stellman · Date: 2026-06-21 · Project: road-rash
//
// Functional tests derived from quality/REQUIREMENTS.md. These exercise the pure,
// dependency-free domain logic that the Lambda handlers and the frontend share.
// They assert SPEC behavior (what the requirements say must happen), not internals.
// Run: pnpm test quality/test_functional.test.ts
//
// Tests for the C1 (email-as-authorName) and C2 (mid encoding) gaps live as
// red/xfail regression tests in quality/test_regression.test.ts (Phase 3), since
// they fail against current code by design.

import { describe, it, expect } from "vitest";
import { validateMyMapsUrl, toMyMapsEmbedUrl } from "../lib/validation";
import { validateTripInput } from "../services/trips/validate";
import { validateFavoriteInput } from "../services/favorites/validate";
import { buildFavoriteCountUpdate } from "../services/favorites/count";
import {
  parsePositiveInt,
  parseSuggestRequest,
  parseSuggestResponse,
  filterToCandidates,
} from "../services/suggest-trips/select";
import { TRIP_TYPES, VEHICLES } from "../lib/types";

const VALID_MY_MAPS = "https://www.google.com/maps/d/edit?mid=1AbC_dEf-2";

const validTripBody = (over: Record<string, unknown> = {}) => ({
  name: "Hai Van Pass Loop",
  description: "Coastal ride",
  location: "Da Nang",
  city: "Da Nang",
  province: "Da Nang",
  country: "Vietnam",
  tripType: "ROAD_TRIP",
  vehicle: "MOTORBIKE",
  durationDays: 3,
  myMapsUrl: VALID_MY_MAPS,
  ...over,
});

// --- Group 1: Spec requirements -------------------------------------------

describe("REQ-002 My Maps URL is host/path/scheme allow-listed", () => {
  it("accepts a genuine My Maps URL (view/edit/embed variants)", () => {
    expect(validateMyMapsUrl(VALID_MY_MAPS)).toBe(true);
    expect(
      validateMyMapsUrl("https://www.google.com/maps/d/viewer?mid=abc123"),
    ).toBe(true);
    expect(
      validateMyMapsUrl("https://www.google.com/maps/d/u/0/edit?mid=abc"),
    ).toBe(true);
  });

  it("rejects non-https, foreign hosts, and look-alike domains", () => {
    expect(validateMyMapsUrl("http://www.google.com/maps/d/edit?mid=abc")).toBe(
      false,
    );
    expect(validateMyMapsUrl("https://evil.com/maps/d/edit?mid=abc")).toBe(
      false,
    );
    expect(
      validateMyMapsUrl("https://www.google.com.evil.com/maps/d/?mid=abc"),
    ).toBe(false);
  });

  it("rejects a plain Maps place URL (not My Maps) and a missing mid", () => {
    expect(
      validateMyMapsUrl("https://www.google.com/maps/place/Hue?mid=abc"),
    ).toBe(false);
    expect(validateMyMapsUrl("https://www.google.com/maps/d/edit")).toBe(false);
    expect(validateMyMapsUrl("https://www.google.com/maps/d/edit?mid=")).toBe(
      false,
    );
  });

  it("rejects javascript: and garbage input without throwing", () => {
    expect(validateMyMapsUrl("javascript:alert(1)")).toBe(false);
    expect(validateMyMapsUrl("not a url")).toBe(false);
    expect(validateMyMapsUrl("")).toBe(false);
  });

  it("canonicalizes any valid variant to the embed endpoint", () => {
    expect(toMyMapsEmbedUrl(VALID_MY_MAPS)).toBe(
      "https://www.google.com/maps/d/embed?mid=1AbC_dEf-2",
    );
    // Always normalizes host + path regardless of the input variant.
    expect(
      toMyMapsEmbedUrl("https://www.google.com/maps/d/u/0/viewer?mid=xyz"),
    ).toBe("https://www.google.com/maps/d/embed?mid=xyz");
  });

  it("throws rather than emitting an unvalidated embed src", () => {
    expect(() => toMyMapsEmbedUrl("https://evil.com/?mid=x")).toThrow();
  });
});

describe("REQ-005 server validates the trip write payload before any DB write", () => {
  it("accepts a well-formed payload and returns a whitelisted value", () => {
    const result = validateTripInput(validTripBody());
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    // Server-owned fields must never appear in the validated value (no mass-assignment).
    for (const key of [
      "id",
      "authorId",
      "authorName",
      "favoriteCount",
      "createdAt",
    ]) {
      expect(key in result.value).toBe(false);
    }
  });

  it("requires name and country", () => {
    expect(validateTripInput(validTripBody({ name: "" })).ok).toBe(false);
    expect(validateTripInput(validTripBody({ country: "" })).ok).toBe(false);
  });

  it("rejects out-of-enum tripType and vehicle", () => {
    expect(validateTripInput(validTripBody({ tripType: "SPACE" })).ok).toBe(
      false,
    );
    expect(validateTripInput(validTripBody({ vehicle: "JETPACK" })).ok).toBe(
      false,
    );
  });

  it("enforces a positive, bounded integer duration", () => {
    expect(validateTripInput(validTripBody({ durationDays: 0 })).ok).toBe(
      false,
    );
    expect(validateTripInput(validTripBody({ durationDays: -1 })).ok).toBe(
      false,
    );
    expect(validateTripInput(validTripBody({ durationDays: 2.5 })).ok).toBe(
      false,
    );
    expect(validateTripInput(validTripBody({ durationDays: 366 })).ok).toBe(
      false,
    );
  });

  it("caps oversized text fields", () => {
    expect(validateTripInput(validTripBody({ name: "x".repeat(121) })).ok).toBe(
      false,
    );
    expect(
      validateTripInput(validTripBody({ description: "x".repeat(2001) })).ok,
    ).toBe(false);
  });

  it("rejects a non-My-Maps URL on the server (defense in depth)", () => {
    expect(
      validateTripInput(validTripBody({ myMapsUrl: "https://evil.com" })).ok,
    ).toBe(false);
  });

  it("every enum member is a valid input (representation completeness)", () => {
    for (const tripType of TRIP_TYPES) {
      expect(validateTripInput(validTripBody({ tripType })).ok).toBe(true);
    }
    for (const vehicle of VEHICLES) {
      expect(validateTripInput(validTripBody({ vehicle })).ok).toBe(true);
    }
  });
});

describe("REQ-003-adjacent favorites input bounds the user-controlled tripId", () => {
  it("accepts a normal trip id and trims it", () => {
    const r = validateFavoriteInput({ tripId: "  t-123  " });
    expect(r.ok).toBe(true);
    if (r.ok) expect(r.value.tripId).toBe("t-123");
  });

  it("rejects missing, non-string, and oversized ids", () => {
    expect(validateFavoriteInput({}).ok).toBe(false);
    expect(validateFavoriteInput({ tripId: 42 }).ok).toBe(false);
    expect(validateFavoriteInput({ tripId: "x".repeat(129) }).ok).toBe(false);
  });
});

describe("REQ-006 AI suggestions stay within the candidate set", () => {
  it("drops ids outside the candidate set and de-duplicates", () => {
    const out = filterToCandidates(
      [{ id: "a" }, { id: "ghost" }, { id: "a" }, { id: "b" }],
      new Set(["a", "b"]),
    );
    expect(out.map((s) => s.id)).toEqual(["a", "b"]);
  });

  it("parses a well-formed request and caps it", () => {
    const raw = JSON.stringify({
      prompt: "quiet beach trip",
      candidates: [{ id: "t1", name: "Beach" }],
      locale: "vi",
    });
    const req = parseSuggestRequest(raw);
    expect(req?.prompt).toBe("quiet beach trip");
    expect(req?.candidates).toHaveLength(1);
    expect(req?.locale).toBe("vi");
  });

  it("rejects requests with no prompt or no candidates", () => {
    expect(
      parseSuggestRequest(JSON.stringify({ candidates: [{ id: "t1" }] })),
    ).toBeUndefined();
    expect(
      parseSuggestRequest(JSON.stringify({ prompt: "x", candidates: [] })),
    ).toBeUndefined();
    expect(parseSuggestRequest("not json")).toBeUndefined();
  });

  it("parses the model envelope and tolerates a bare array / code fence", () => {
    expect(
      parseSuggestResponse('{"summary":"Try Hue.","results":[{"id":"t1"}]}'),
    ).toEqual({ summary: "Try Hue.", suggestions: [{ id: "t1" }] });
    expect(parseSuggestResponse('```json\n[{"id":"t2"}]\n```')).toEqual({
      summary: "",
      suggestions: [{ id: "t2" }],
    });
    expect(parseSuggestResponse("garbage")).toEqual({
      summary: "",
      suggestions: [],
    });
  });
});

// --- Group 2: Fitness scenarios (from QUALITY.md) -------------------------

describe("FIT: timeout env parse can never yield a 0ms abort", () => {
  it("falls back for non-numeric / zero / negative overrides", () => {
    expect(parsePositiveInt(undefined, 20000)).toBe(20000);
    expect(parsePositiveInt("abc", 20000)).toBe(20000);
    expect(parsePositiveInt("0", 20000)).toBe(20000);
    expect(parsePositiveInt("-5", 20000)).toBe(20000);
    expect(parsePositiveInt("5000", 20000)).toBe(5000);
  });
});

describe("FIT: denormalized favoriteCount update is guarded", () => {
  it("increment only requires the trip to exist", () => {
    const cmd = buildFavoriteCountUpdate("Trip", "t1", 1);
    expect(cmd.ConditionExpression).toBe("attribute_exists(id)");
    expect(cmd.UpdateExpression).toContain(
      "if_not_exists(favoriteCount, :zero)",
    );
    expect(cmd.ExpressionAttributeValues?.[":delta"]).toBe(1);
  });

  it("decrement is floored so the counter never goes negative", () => {
    const cmd = buildFavoriteCountUpdate("Trip", "t1", -1);
    expect(cmd.ConditionExpression).toContain("favoriteCount > :zero");
    expect(cmd.ExpressionAttributeValues?.[":delta"]).toBe(-1);
  });
});

// --- Group 3: Boundaries and edge cases -----------------------------------

describe("BOUND: validators reject non-object bodies without throwing", () => {
  it("trip + favorite validators handle null/array/primitive input", () => {
    for (const bad of [null, undefined, 42, "str", []]) {
      expect(validateTripInput(bad as unknown).ok).toBe(false);
      expect(validateFavoriteInput(bad as unknown).ok).toBe(false);
    }
  });
});
