// Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
// Author: Andrew Stellman · Date: 2026-06-21 · Project: road-rash
//
// Regression tests for confirmed bugs (Phase 3). Each asserts the DESIRED
// (post-fix) behavior and is marked `test.fails(...)` — Vitest's strict-xfail:
// while the bug is present the assertion fails and the suite stays green; once
// the fix lands the assertion passes, `test.fails` then FAILS, signalling that
// the marker must be removed and the bug closed.
//
// Run: pnpm test quality/test_regression.test.ts
// Fix patches: quality/patches/BUG-00{1,2,3}-fix.patch (drafts in SUGGESTED_CHANGES.md)

import { describe, it, test, expect } from "vitest";
import { validateMyMapsUrl, toMyMapsEmbedUrl } from "../lib/validation";
import { validateTripInput } from "../services/trips/validate";
import { getDisplayName } from "../services/shared/auth";

const validTripBody = (over: Record<string, unknown> = {}) => ({
  name: "Hai Van Pass Loop",
  location: "Da Nang",
  city: "Da Nang",
  province: "Da Nang",
  country: "Vietnam",
  tripType: "ROAD_TRIP",
  vehicle: "MOTORBIKE",
  durationDays: 3,
  myMapsUrl: "https://www.google.com/maps/d/edit?mid=1AbC_dEf-2",
  ...over,
});

const eventWithClaims = (claims: Record<string, unknown>) =>
  ({ requestContext: { authorizer: { jwt: { claims } } } }) as never;

describe("BUG-001 (REQ-001 / C1): email must never become a public authorName", () => {
  // Spec basis: REQUIREMENTS.md REQ-001 — authorName on public reads must not be email.
  test.fails(
    "getDisplayName must NOT return the email when no name claim is present",
    () => {
      const label = getDisplayName(
        eventWithClaims({ email: "secret@user.com" }),
      );
      // Current code returns the email (fails); fix returns cognito:username/sub/"Unknown".
      expect(label).not.toBe("secret@user.com");
      expect(label).not.toMatch(/@/);
    },
  );

  it("still returns the name when a name claim IS present (no regression)", () => {
    expect(
      getDisplayName(eventWithClaims({ name: "Huy", email: "h@x.com" })),
    ).toBe("Huy");
  });
});

describe("BUG-002 (REQ-002 / C2): the embed mid must be structurally safe", () => {
  // Spec basis: REQUIREMENTS.md REQ-002 — embed src canonical with an encoded mid.
  test.fails(
    "validateMyMapsUrl must reject a mid with a reserved/space char",
    () => {
      // searchParams decodes %20 → "a b"; current code accepts any non-empty mid.
      const url = "https://www.google.com/maps/d/viewer?mid=a%20b";
      expect(validateMyMapsUrl(url)).toBe(false);
    },
  );

  test.fails("toMyMapsEmbedUrl must not emit a raw '&' from the mid", () => {
    // A mid containing '&' would inject an extra query param into the embed URL.
    const url = "https://www.google.com/maps/d/edit?mid=a%26b"; // decoded: "a&b"
    // If the validator is tightened this throws (also acceptable); otherwise the
    // output must encode the '&' rather than emit it raw.
    const out = toMyMapsEmbedUrl(url);
    expect(out).not.toContain("mid=a&b");
  });
});

describe("BUG-003 (REQ-003 / C3): thumbnailKey must reference the thumbnails namespace", () => {
  // Spec basis: REQUIREMENTS.md REQ-003 — thumbnailKey within the caller's namespace.
  test.fails(
    "validateTripInput must reject a thumbnailKey outside thumbnails/",
    () => {
      const result = validateTripInput(
        validTripBody({ thumbnailKey: "etc/passwd.jpg" }),
      );
      expect(result.ok).toBe(false);
    },
  );

  it("accepts a thumbnailKey inside the thumbnails namespace (no regression)", () => {
    const result = validateTripInput(
      validTripBody({ thumbnailKey: "thumbnails/abc/def.jpg" }),
    );
    expect(result.ok).toBe(true);
  });
});
