// Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
// Author: Andrew Stellman · Date: 2026-06-21 · Project: road-rash
//
// Regression guards for BUG-001/002/003 (found in Phase 3, fixed and closed).
// Each asserts the post-fix behavior and now passes against the source — they
// guard against re-introduction. (They were authored as `test.fails` xfail
// markers while the bugs were open, then flipped to passing `it` tests when the
// corresponding fix landed.)
//
// Run: pnpm test quality/test_regression.test.ts
// History: quality/BUGS.md, quality/writeups/BUG-00{1,2,3}.md

import { describe, it, expect } from "vitest";
import { validateMyMapsUrl, toMyMapsEmbedUrl } from "../lib/validation";
import { validateTripInput } from "../services/trips/validate";
import { getDisplayName } from "../services/shared/auth";

const validTripBody = (over: Record<string, unknown> = {}) => ({
  name: "Hai Van Pass Loop",
  location: "Da Nang",
  city: "Da Nang",
  province: "Da Nang",
  country: "Vietnam",
  tripType: "ROAD_TRIP",
  vehicle: "MOTORBIKE",
  durationDays: 3,
  myMapsUrl: "https://www.google.com/maps/d/edit?mid=1AbC_dEf-2",
  ...over,
});

const eventWithClaims = (claims: Record<string, unknown>) =>
  ({ requestContext: { authorizer: { jwt: { claims } } } }) as never;

describe("BUG-001 (REQ-001 / C1): email must never become a public authorName", () => {
  // Spec basis: REQUIREMENTS.md REQ-001 — authorName on public reads must not be email.
  // FIXED: getDisplayName no longer falls back to email (services/shared/auth.ts).
  it("getDisplayName must NOT return the email when no name claim is present", () => {
    const label = getDisplayName(eventWithClaims({ email: "secret@user.com" }));
    expect(label).not.toBe("secret@user.com");
    expect(label).not.toMatch(/@/);
  });

  it("still returns the name when a name claim IS present (no regression)", () => {
    expect(
      getDisplayName(eventWithClaims({ name: "Huy", email: "h@x.com" })),
    ).toBe("Huy");
  });
});

describe("BUG-002 (REQ-002 / C2): the embed mid must be structurally safe", () => {
  // Spec basis: REQUIREMENTS.md REQ-002 — embed src canonical with an encoded mid.
  // FIXED: validateMyMapsUrl now charset-checks the mid; toMyMapsEmbedUrl encodes it.
  it("validateMyMapsUrl rejects a mid with a reserved/space char", () => {
    // searchParams decodes %20 → "a b"; the charset check now rejects it.
    expect(
      validateMyMapsUrl("https://www.google.com/maps/d/viewer?mid=a%20b"),
    ).toBe(false);
    expect(
      validateMyMapsUrl("https://www.google.com/maps/d/edit?mid=a%26b"),
    ).toBe(false);
  });

  it("toMyMapsEmbedUrl never emits a structure-altering mid (throws on hostile input)", () => {
    // The tightened validator makes the builder throw rather than emit a raw '&'.
    expect(() =>
      toMyMapsEmbedUrl("https://www.google.com/maps/d/edit?mid=a%26b"),
    ).toThrow();
    // A genuine URL-safe mid round-trips unchanged.
    expect(
      toMyMapsEmbedUrl("https://www.google.com/maps/d/edit?mid=1AbC_dEf-2"),
    ).toBe("https://www.google.com/maps/d/embed?mid=1AbC_dEf-2");
  });
});

describe("BUG-003 (REQ-003 / C3): thumbnailKey must reference the thumbnails namespace", () => {
  // Spec basis: REQUIREMENTS.md REQ-003 — thumbnailKey within the caller's namespace.
  // FIXED: validateTripInput now rejects keys outside the thumbnails/ namespace.
  it("validateTripInput rejects a thumbnailKey outside thumbnails/", () => {
    const result = validateTripInput(
      validTripBody({ thumbnailKey: "etc/passwd.jpg" }),
    );
    expect(result.ok).toBe(false);
  });

  it("accepts a thumbnailKey inside the thumbnails namespace (no regression)", () => {
    const result = validateTripInput(
      validTripBody({ thumbnailKey: "thumbnails/abc/def.jpg" }),
    );
    expect(result.ok).toBe(true);
  });
});
