import { type Variation, seedVariations } from "./seed-trips";

// A third batch of 24 example trips spanning the rest of the world (Europe,
// the Americas, Oceania, Africa, and the Middle East / Central Asia), to give
// the country / province / city filters and grouping global variety to test
// against. Like the earlier batches, each derives its map from an existing
// trip's My Maps URL (the app can't create My Maps programmatically) and
// renders the placeholder thumbnail. Run the same way — see
// scripts/README-seed.md.
const EVEN_MORE_VARIATIONS: Variation[] = [
  {
    name: "Amalfi Coast Drive",
    location: "Amalfi Coastal Road",
    city: "Positano",
    province: "Salerno",
    country: "Italy",
    tripType: "ROAD_TRIP",
    vehicle: "CAR",
    durationDays: 4,
    description:
      "Cliff-hugging hairpins, lemon groves, and pastel seaside towns.",
  },
  {
    name: "Tuscany Vineyard Loop",
    location: "Chianti Hills",
    city: "Greve in Chianti",
    province: "Florence",
    country: "Italy",
    tripType: "FOOD",
    vehicle: "CAR",
    durationDays: 3,
    description:
      "Cypress-lined roads, hilltop wineries, and long farmhouse lunches.",
  },
  {
    name: "Scottish Highlands Run",
    location: "North Coast 500",
    city: "Inverness",
    province: "Highland",
    country: "United Kingdom",
    tripType: "ROAD_TRIP",
    vehicle: "CAR",
    durationDays: 5,
    description: "Lochs, single-track passes, and windswept castle ruins.",
  },
  {
    name: "Andalusia White Villages",
    location: "Pueblos Blancos",
    city: "Ronda",
    province: "Malaga",
    country: "Spain",
    tripType: "CITY",
    vehicle: "MOTORBIKE",
    durationDays: 3,
    description: "Whitewashed hill towns, gorges, and Moorish old quarters.",
  },
  {
    name: "Bavarian Alps Escape",
    location: "Berchtesgaden Land",
    city: "Berchtesgaden",
    province: "Bavaria",
    country: "Germany",
    tripType: "MOUNTAIN",
    vehicle: "CAR",
    durationDays: 4,
    description:
      "Alpine lakes, salt-mine villages, and fairytale castle views.",
  },
  {
    name: "Norwegian Fjords Ferry Trip",
    location: "Geirangerfjord",
    city: "Geiranger",
    province: "More og Romsdal",
    country: "Norway",
    tripType: "ROAD_TRIP",
    vehicle: "OTHER",
    durationDays: 5,
    description:
      "Waterfall walls, switchback roads, and deep blue fjord crossings.",
  },
  {
    name: "Provence Lavender Pedal",
    location: "Valensole Plateau",
    city: "Valensole",
    province: "Alpes-de-Haute-Provence",
    country: "France",
    tripType: "CITY",
    vehicle: "BICYCLE",
    durationDays: 2,
    description: "Purple fields, stone villages, and slow market mornings.",
  },
  {
    name: "Iceland Ring Road",
    location: "Route 1",
    city: "Reykjavik",
    province: "Capital Region",
    country: "Iceland",
    tripType: "ROAD_TRIP",
    vehicle: "CAR",
    durationDays: 7,
    description:
      "Waterfalls, black-sand beaches, glaciers, and geothermal valleys.",
  },
  {
    name: "Pacific Coast Highway",
    location: "Big Sur Coast",
    city: "Monterey",
    province: "California",
    country: "United States",
    tripType: "ROAD_TRIP",
    vehicle: "CAR",
    durationDays: 4,
    description:
      "Sea-cliff bridges, redwoods, and surf-town stops down Highway 1.",
  },
  {
    name: "Utah Canyon Camping",
    location: "Zion National Park",
    city: "Springdale",
    province: "Utah",
    country: "United States",
    tripType: "CAMPING",
    vehicle: "OTHER",
    durationDays: 3,
    description: "Slot canyons, red rock walls, and star-filled desert nights.",
  },
  {
    name: "Banff Rockies Drive",
    location: "Icefields Parkway",
    city: "Banff",
    province: "Alberta",
    country: "Canada",
    tripType: "MOUNTAIN",
    vehicle: "CAR",
    durationDays: 4,
    description:
      "Turquoise lakes, glaciers, and elk-crossed mountain highways.",
  },
  {
    name: "Patagonia Trail Camp",
    location: "Torres del Paine",
    city: "Puerto Natales",
    province: "Magallanes",
    country: "Chile",
    tripType: "CAMPING",
    vehicle: "OTHER",
    durationDays: 6,
    description:
      "Granite towers, glacial lakes, and wind-blasted trekking trails.",
  },
  {
    name: "Mexico City Taco Crawl",
    location: "Roma Norte",
    city: "Mexico City",
    province: "Mexico City",
    country: "Mexico",
    tripType: "FOOD",
    vehicle: "BICYCLE",
    durationDays: 2,
    description: "Street tacos, cantinas, and leafy art-deco neighborhoods.",
  },
  {
    name: "Rio Beaches Cruise",
    location: "Copacabana",
    city: "Rio de Janeiro",
    province: "Rio de Janeiro",
    country: "Brazil",
    tripType: "BEACH",
    vehicle: "CAR",
    durationDays: 3,
    description: "Golden sands, mountain backdrops, and a coastal samba beat.",
  },
  {
    name: "Cusco to Sacred Valley",
    location: "Sacred Valley of the Incas",
    city: "Cusco",
    province: "Cusco",
    country: "Peru",
    tripType: "MOUNTAIN",
    vehicle: "OTHER",
    durationDays: 4,
    description: "Andean ruins, terraced hillsides, and high-altitude markets.",
  },
  {
    name: "Great Ocean Road",
    location: "Twelve Apostles",
    city: "Apollo Bay",
    province: "Victoria",
    country: "Australia",
    tripType: "ROAD_TRIP",
    vehicle: "CAR",
    durationDays: 3,
    description:
      "Surf coast cliffs, rainforest detours, and limestone sea stacks.",
  },
  {
    name: "Outback Red Centre Run",
    location: "Uluru-Kata Tjuta",
    city: "Yulara",
    province: "Northern Territory",
    country: "Australia",
    tripType: "CAMPING",
    vehicle: "OTHER",
    durationDays: 4,
    description:
      "Desert highways, sacred monoliths, and vast star-lit campsites.",
  },
  {
    name: "South Island Alpine Loop",
    location: "Southern Alps",
    city: "Queenstown",
    province: "Otago",
    country: "New Zealand",
    tripType: "MOUNTAIN",
    vehicle: "CAR",
    durationDays: 5,
    description:
      "Glacier valleys, mirror lakes, and adrenaline mountain towns.",
  },
  {
    name: "Cape Town Coastal Drive",
    location: "Chapman's Peak",
    city: "Cape Town",
    province: "Western Cape",
    country: "South Africa",
    tripType: "BEACH",
    vehicle: "CAR",
    durationDays: 3,
    description:
      "Table Mountain views, penguin beaches, and a cliffside ocean road.",
  },
  {
    name: "Marrakech Medina Wander",
    location: "Medina Quarter",
    city: "Marrakech",
    province: "Marrakech-Safi",
    country: "Morocco",
    tripType: "CITY",
    vehicle: "OTHER",
    durationDays: 2,
    description:
      "Souk mazes, riad courtyards, and spice-scented night squares.",
  },
  {
    name: "Atlas Mountains Berber Trek",
    location: "High Atlas",
    city: "Imlil",
    province: "Marrakech-Safi",
    country: "Morocco",
    tripType: "MOUNTAIN",
    vehicle: "OTHER",
    durationDays: 4,
    description:
      "Mud-brick villages, mule trails, and snow-capped Toubkal passes.",
  },
  {
    name: "Wadi Rum Desert Camp",
    location: "Wadi Rum Protected Area",
    city: "Aqaba",
    province: "Aqaba",
    country: "Jordan",
    tripType: "CAMPING",
    vehicle: "OTHER",
    durationDays: 2,
    description: "Sandstone canyons, Bedouin camps, and Martian-red dunes.",
  },
  {
    name: "Cappadocia Valley Ride",
    location: "Goreme Valley",
    city: "Goreme",
    province: "Nevsehir",
    country: "Turkey",
    tripType: "MOUNTAIN",
    vehicle: "MOTORBIKE",
    durationDays: 3,
    description: "Fairy chimneys, cave towns, and dawn balloon-filled skies.",
  },
  {
    name: "Tbilisi to Kazbegi",
    location: "Georgian Military Highway",
    city: "Tbilisi",
    province: "Tbilisi",
    country: "Georgia",
    tripType: "ROAD_TRIP",
    vehicle: "CAR",
    durationDays: 3,
    description:
      "Caucasus passes, hillside monasteries, and old-town wine cellars.",
  },
];

// `import.meta.url` matches the invoked file only when run directly via tsx.
if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  seedVariations(EVEN_MORE_VARIATIONS).catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
